/** Alt text for every photograph, describing the people and the place. Keyed by file name in public/assets/photos. */
export const PHOTO_ALT: Record<string, string> = {
  "accountant-man.jpg": "A smiling young man in a white shirt holds a laptop beside a large window in a bright modern office.",
  "accounts-desk.jpg": "A woman in an orange blazer writes in a notebook at an office desk covered with charts.",
  "assembly.jpg": "Primary pupils in white shirts and navy uniforms gather in a crowded school courtyard, some sitting and some standing.",
  "boys-laptop.jpg": "Two boys in checked school shirts work together on a laptop at wooden desks in a classroom.",
  "boys-reading-2.jpg": "Four teenage boys in khaki uniforms look at an exercise book together beside a palm tree in a school courtyard.",
  "boys-reading.jpg": "Four secondary pupils in khaki uniforms share a notebook and smile under a palm in an arcaded school courtyard.",
  "bursar-laptop.jpg": "A smiling woman in a red dress works at a laptop, phone beside her, at a bright office desk.",
  "child-doorway.jpg": "A young girl in a blue school dress with a white collar stands in a worn metal doorway.",
  "class-desks.jpg": "Rows of pupils in pale yellow shirts sit at wooden desks under a large tent, with adults standing behind.",
  "classroom-uniforms.jpg": "Teenage pupils in white shirts sit closely packed at wooden desks in a sunlit classroom, listening.",
  "classroom-zambia.jpg": "Secondary pupils in blue shirts work at shared desks in a busy classroom, seen through an open doorway.",
  "day-pupils.jpg": "Four young children in orange shirts with school bags chat beside a block wall on a sandy street.",
  "ecd-class.jpg": "A teacher points to the alphabet on a chalkboard while young children in red shirts write at small tables.",
  "ecocash-icon.png": "EcoCash",
  "exam-blue.jpg": "Secondary pupils in blue shirts sit spaced apart at wooden desks, writing an exam in a classroom.",
  "family-sofa.jpg": "A woman on the phone sits on a sofa at home beside a girl while a boy peeks over.",
  "father-son.jpg": "A smiling young man in a white shirt holds a laughing baby outdoors on a grassy field.",
  "girl-beret.jpg": "A smiling teenage girl in a maroon school beret, jumper and striped tie stands outdoors.",
  "girl-desk.jpg": "A smiling teenage girl in a white school shirt writes at her desk among classmates in a classroom.",
  "girls-backpacks.jpg": "Teenage girls in white shirts with backpacks queue in a school hall, one smiling at the front.",
  "girls-classroom.jpg": "Teenage girls in white blouses and blue skirts file through a school hall carrying bags and papers.",
  "girls-desks.jpg": "Young girls in blue school uniforms, one wearing a white headscarf, sit at a wooden desk in a classroom.",
  "girls-laughing.jpg": "Teenage girls in white school shirts laugh together while queuing in a crowded school hall.",
  "girls-papers.jpg": "Teenage pupils in white shirts with blue collars share a reading booklet at a wooden desk in a hall.",
  "girls-smiling.jpg": "Young pupils in blue checked shirts line up outdoors with backpacks, a smiling girl looking back at the camera.",
  "head-desk.jpg": "A man in glasses and a striped shirt listens at a meeting table with a notebook and laptop.",
  "kids-laptop.jpg": "Two boys in checked school shirts look at photos on a laptop at a wooden desk in a classroom.",
  "kids-lunch.jpg": "Young girls in green school jumpers eat lunch at a classroom table, seen through open glass doors.",
  "lining-up.jpg": "Teenage girls in white tops and blue skirts queue with backpacks inside a school hall.",
  "man-laptop.jpg": "A smiling bearded man in a mustard jumper types on a laptop at a wooden table in a bright office.",
  "mission-pupils.jpg": "Primary children in white uniforms, many girls in white headscarves, crowd together in a school yard.",
  "mother-child.jpg": "A woman in a green patterned dress and matching headwrap holds a toddler in a green T-shirt.",
  "mother-phone.jpg": "A woman in a headwrap checks her phone on a pink sofa at home while a girl does homework nearby.",
  "office-desk.jpg": "A smiling woman in a white shirt and black tie rests her chin on her hand at a desk.",
  "office-documents.jpg": "A young woman with curly hair sorts through papers at a cluttered office desk with a computer.",
  "office-papers.jpg": "A woman in a striped blazer reads handwritten notes beside a laptop at a wooden office desk.",
  "office-phone.jpg": "A woman in a striped blazer talks on the phone in front of a tablet in a dimly lit office.",
  "pupils-marks.jpg": "Teenage pupils in white shirts with purple collars read a booklet together at a wooden desk in a hall.",
  "pupils-walking.jpg": "Smiling pupils in lime-green polo shirts and black shorts walk along a dirt path carrying books and bags.",
  "pupils-writing.jpg": "Secondary pupils in white and khaki uniforms chat and write at their desks in a classroom.",
  "rural-school.jpg": "Five teenage pupils in white shirts stand together on a grassy path in front of a rural school building.",
  "seniors-lecture.jpg": "Older secondary pupils in white shirts with red collars sit in rows, listening attentively at a school gathering.",
  "sports-day.jpg": "Primary pupils in coloured uniforms stand in lines on a dusty school field as a girl leads an exercise.",
  "staff-laptop.jpg": "A man in a lilac shirt works on a laptop at a wooden table in a bright room.",
  "teacher-board.jpg": "A teacher in a black blazer smiles while writing in chalk on a classroom blackboard.",
  "teacher-class.jpg": "A teacher smiles as a boy stands by a whiteboard diagram and a girl raises her hand in class.",
  "teacher-garden.jpg": "A man in glasses and a dark jacket poses with three smiling teenage girls in school uniform in a garden.",
  "teacher-maths.jpg": "A smiling woman in a checked blazer sits at a desk in front of a whiteboard of maths problems.",
  "teacher-notebook.jpg": "A smiling young woman in a fox-print blouse holds an open notebook in a bright classroom.",
  "teacher-tablet.jpg": "A teacher in a dark blazer reads from a clipboard in front of a chalkboard covered in geometry formulas.",
  "teens-courtyard.jpg": "A group of young teenagers in casual sportswear pose together in a paved courtyard between school buildings.",
  "woman-files.jpg": "A woman in a white blouse holds a stack of black ring binders beside a glass office partition.",
  "zimra-mark.png": "ZIMRA",
};
