# -*- coding: utf-8 -*-
"""Copy for every page in the navigation tree, beyond Home, Academics and Moving (words.py).
Written through ux-writing, then sepia and plain-prose: British English, active voice, you, no empty qualifiers.
Price is always "US$1 per active pupil per month". Nothing here claims schools, quotes or figures we cannot back."""

# Department pages. pic: ("photo", file, position, [cards]) or ("plate", [cards], art key or None)
# cards are (name of a site_cards function or a ui card, x, y)
DEPTS = {
    "admissions": dict(
        h="From the first enquiry to the first day of term.",
        b="Take enquiries, applications and Form 1 places in one place. The pupil's record starts with the application, so nobody types the family's details twice.",
        hero=("office-phone.jpg", "center 30%", "application_card", "intake_card"),
        band=("The record starts on the application form.",
              "The guardian's details, the Grade 7 results and the documents you collect stay on the pupil's record after they accept. Fees, the class list and the Parent portal all start from it.",
              "girl-desk.jpg", "center 35%"),
        rows=[("Enquiries", "admissions", "Answer every enquiry and know where it came from.",
               "Log each phone call, walk-in and web form against the family. You see who to call back and which open day brought them in.",
               ("plate", [("intake_card", 150, 40)], None)),
              ("Tests and interviews", "record", "Run entrance tests and interviews from one list.",
               "Book applicants into a test sitting, record their marks and interview notes, and rank them against the places you have.",
               ("photo", "pupils-marks.jpg", "center 40%", [("application_card", 0, 70)])),
              ("Offers", "sent", "Send offers and see who has accepted.",
               "Offer letters go to the guardian with the deposit due. When the deposit is paid, the pupil joins the class list and the family gets a Parent portal sign-in.",
               ("plate", [("offer_card", 40, 40)], "admissions"))],
        tools=["Enquiries and open days", "Online application form", "Document checklist", "Entrance tests and interviews", "Waiting lists",
               "Offer letters", "Deposits linked to fees", "Sibling links", "Class lists for the new year", "Transfers in and out"],
    ),
    "fees": dict(
        h="Every payment matched to a pupil.",
        b="Bill each family in US dollars and ZiG. EcoCash, bank transfers and cash at the bursary land on the right account with a receipt number.",
        hero=("bursar-laptop.jpg", "center 30%", "payments_card", "fee_card"),
        band=("The bursar and the family see the same balance.",
              "Each payment updates the pupil's account as it lands. The Parent portal shows the balance the bursary sees, with a receipt for every payment.",
              "mother-child.jpg", "center 30%"),
        rows=[("Billing", "fees", "Bill the whole school at the start of term.",
               "Set the fee structure once by form, boarding and transport. Campus bills every family, applies sibling discounts and keeps the currency each fee is set in.",
               ("plate", [("billing_card", 150, 30)], None)),
              ("Payments", "record", "Match payments without retyping them.",
               "EcoCash and bank payments arrive with a reference and match to the pupil. Cash at the bursary gets a numbered receipt on the spot.",
               ("photo", "family-sofa.jpg", "65% center", [("payments_card", 0, 90)])),
              ("Arrears", "insights", "See who owes, by form and by family.",
               "Arrears by form, family and day, with reminders sent from Campus. You call the families who need a call, not every family.",
               ("plate", [("arrears_card", 40, 40)], "fees"))],
        tools=["Fee structures by form", "Boarding and transport fees", "US dollars and ZiG", "EcoCash and bank matching", "Numbered receipts",
               "Sibling discounts and bursaries", "Statements for families", "Reminders", "Payment plans", "ZIMRA fiscal receipts"],
    ),
    "accounting": dict(
        h="The school's books, kept with the fees.",
        b="Campus posts fees, payroll and purchases to the ledger as they happen. Send journals to Sage Pastel or QuickBooks, and issue fiscal receipts through ZIMRA.",
        hero=("office-papers.jpg", "center 30%", "ledger_card", "journal_card"),
        band=("Your accountant works from the bursary's figures.",
              "Every receipt, payslip and purchase order is already on the record. Month-end starts with the books up to date, not with a pile of receipts.",
              "accountant-man.jpg", "center 30%"),
        rows=[("Ledger", "accounting", "Keep the ledger current as the school runs.",
               "Fees, payroll and purchases post to your chart of accounts as they happen. You see income and spending by fund, term and department.",
               ("plate", [("ledger_card", 150, 40)], None)),
              ("Integrations", "integrations", "Send journals to Sage Pastel or QuickBooks.",
               "Campus sends a journal at the end of each day or month, in the format your accountant uses. Nobody retypes a receipt.",
               ("integrations",)),
              ("Fiscalisation", "pricesheet", "Issue fiscal receipts through ZIMRA.",
               "Campus issues fiscal receipts through ZIMRA's Fiscalisation Data Management System, with the verification code printed on every receipt.",
               ("plate", [("fiscal_card", 40, 40)], "accounting"))],
        tools=["Chart of accounts", "Funds and cost centres", "Purchase orders", "Supplier payments", "Bank reconciliation",
               "Budgets by department", "Journals to Sage Pastel", "Journals to QuickBooks", "ZIMRA fiscal receipts", "A record of every change"],
    ),
    "hr-payroll": dict(
        h="Pay every member of staff from one record.",
        b="Staff records, contracts, leave and a monthly payroll in one place. Payslips go out on payday and the journal goes to the books.",
        hero=("staff-laptop.jpg", "center 30%", "staff_card", "payslip_card"),
        band=("One record for every member of staff.",
              "Contracts, qualifications, leave and bank details sit on one record. Payroll reads it, so a change in the office reaches the next payslip.",
              "office-documents.jpg", "center 30%"),
        rows=[("Staff records", "hr-payroll", "Keep every contract and qualification in one place.",
               "Teaching and support staff, with contracts, qualifications, next of kin and documents. You see whose contract ends this term.",
               ("plate", [("staff_card", 160, 40)], None)),
              ("Leave", "calendar-t", "Approve leave from the staffroom.",
               "Staff request leave from the Teacher portal. The Head approves it, the balance updates and cover goes on the timetable.",
               ("photo", "teacher-board.jpg", "center 30%", [("leave_card", 0, 80)])),
              ("Payroll", "fees", "Run payroll in an afternoon.",
               "Allowances, PAYE, AIDS levy and NSSA come from the staff record. You approve the run, payslips go out and the journal posts to the books.",
               ("plate", [("payrun_card", 40, 40)], "hr"))],
        tools=["Staff records", "Contracts and renewals", "Qualifications", "Leave requests and balances", "Cover",
               "Monthly payroll", "PAYE, AIDS levy and NSSA", "Payslips in the portal", "Bank payment lists", "Payroll journals"],
    ),
    "boarding": dict(
        h="Every boarder accounted for, morning and night.",
        b="Houses, roll call, exeats and the sick bay on each boarder's record. Housemasters and the office work from the same list.",
        hero=("lining-up.jpg", "center 40%", "rollcall_card", "exeat_card"),
        band=("The hostel works from the same record as the classroom.",
              "A boarder's house, room, guardians and fees sit on one record. When a pupil signs out on exeat, the house list and the duty teacher know.",
              "kids-lunch.jpg", "center 40%"),
        rows=[("Roll call", "boarding", "Take roll call in minutes, house by house.",
               "Mark each boarder on a phone at prep and lights out. Anyone missing shows straight away, and roll call works without internet.",
               ("plate", [("rollcall_card", 160, 40)], None)),
              ("Exeats", "sent", "Approve exeats and know who is out.",
               "Guardians request exeats from the Parent portal. The housemaster approves, and you see who signed out, who collected them and when they are due back.",
               ("photo", "girls-laughing.jpg", "center 35%", [("exeat_card", 0, 80)])),
              ("Sick bay", "support", "Keep the sick bay's log on the record.",
               "Matron logs each visit and tells the guardian from Campus. Class teachers see who is off lessons.",
               ("plate", [("sickbay_card", 40, 40)], "boarding"))],
        tools=["Houses and rooms", "Roll call", "Exeats and outings", "Visiting days", "Sick bay log",
               "Duty rosters", "Boarding fees", "Tuck shop accounts", "Messages to boarding families", "Works without internet"],
    ),
    "stock": dict(
        h="Know what is in the stores and who has it.",
        b="Stores, uniforms, textbooks and repairs in one place. Every item is issued against a name, so you know what is out and what to reorder.",
        hero=("classroom-uniforms.jpg", "center", "stock_card", "issue_card"),
        band=("Issue an item once and the record keeps track.",
              "A textbook issued to Tanaka stays on his record until he returns it. Uniform sales go to the family's fee account.",
              "girls-backpacks.jpg", "center 35%"),
        rows=[("Stores", "stock", "See stock levels before you run out.",
               "Stationery, cleaning supplies and food stores with quantities and reorder levels. Purchase orders go to suppliers and post to the books.",
               ("plate", [("stock_card", 150, 40)], None)),
              ("Textbooks and uniforms", "academics", "Issue textbooks and uniforms against a name.",
               "Pick each item as you hand it out. Uniform sales go to the family's fee account, and textbooks come back at the end of the year.",
               ("photo", "class-desks.jpg", "center 40%", [("issue_card", 0, 80)])),
              ("Repairs", "support", "Log repairs and see them through.",
               "Staff report a broken window or a leaking tap from any portal. The bursar assigns it and sees what each repair cost.",
               ("plate", [("repairs_card", 40, 40)], "stock"))],
        tools=["Stores and stock levels", "Reorder levels", "Purchase orders", "Suppliers", "Textbook issue and returns",
               "Uniform shop", "Asset register", "Repairs", "Lab and sports equipment", "Stock takes"],
    ),
    "communication": dict(
        h="Reach one parent, a class or every family.",
        b="Send messages, newsletters and reminders from Campus. Replies go to the class teacher, and you see who has read them.",
        hero=("mother-child.jpg", "center 25%", "compose_card", "note_card"),
        band=("Every message lands with the right family.",
              "Campus knows each pupil's guardians, class and house, so a message to Form 3B reaches the right parents. Every message stays on the record.",
              "day-pupils.jpg", "center 40%"),
        rows=[("Messages", "communication", "Message one guardian or a whole class.",
               "Choose a pupil, a form, a house or the whole school. Parents read it in the Parent portal and reply to the teacher who sent it.",
               ("plate", [("compose_card", 140, 50)], None)),
              ("Dates and events", "calendar-t", "Put the term's dates on every parent's phone.",
               "Send the newsletter, sports fixtures and the term's dates. Parents see them in the portal, with a reminder the day before.",
               ("photo", "sports-day.jpg", "center 35%", [("events_card", 0, 80)])),
              ("Read receipts", "sent", "Know who has read it.",
               "See who has opened each message and follow up with the families who have not.",
               ("plate", [("read_card", 40, 40)], "comms"))],
        tools=["Messages to guardians", "Class and house groups", "Newsletters", "Term calendar", "Event reminders",
               "Read receipts", "Replies to the class teacher", "Consent forms", "Urgent notices", "Message history on the record"],
    ),
    "insights": dict(
        h="The whole school on one screen.",
        b="Attendance, fees, marks and staffing for the Head, the SDC and the board. The figures come from the record, so they are current.",
        hero=("head-desk.jpg", "center 30%", "attendance_card", "collected_card"),
        band=("Answer the board's questions before the meeting.",
              "Every figure opens the records behind it. When the SDC asks why fees collected dropped, you open the list of families, not a spreadsheet.",
              "exam-blue.jpg", "center 40%"),
        rows=[("Attendance", "insights", "See attendance across the school by 08:05.",
               "Attendance by form, house and day, with the pupils who have missed the most. You see a pattern before the end of term.",
               ("plate", [("attendance_card", 150, 40)], None)),
              ("Fees", "fees", "Know fees collected against fees billed.",
               "Collections by term, form and currency, with arrears and cash flow for the bursar and the board.",
               ("photo", "assembly.jpg", "center 40%", [("collected_card", 0, 80)])),
              ("Results", "record", "Compare results by subject and form.",
               "Averages and pass rates by subject, form and teacher, term on term. You see where a class needs help.",
               ("plate", [("results_card", 40, 40)], "insights"))],
        tools=["The Head's view", "Attendance by form and house", "Fees collected and arrears", "Results by subject and form", "Staffing and leave",
               "Enrolment and admissions", "Reports for the SDC and board", "Export to Excel", "Saved views", "Every figure opens its records"],
    ),
}
DEPT_TOOLS_H = "What it covers"

# School types. depts: slugs shown as tiles
TYPES = {
    "t-day": dict(
        name="Day schools", h="Know who is in school by 08:05.",
        b="Registers, fees billed by family and transport lists for day schools, primary and secondary. Parents see the day on their phone.",
        hero=("pupils-walking.jpg", "center 40%", "register_card", "note_card"),
        depts=["academics", "fees", "communication", "admissions", "stock", "insights"],
        rows=[("Registers", "academics", "Tell parents about absences the same morning.",
               "Teachers mark the register before the first lesson. The office sees who is absent by 08:05 and messages those families from Campus.",
               ("plate", [("register_card", 150, 30)], None)),
              ("Transport", "t-day", "Keep bus lists on the pupil's record.",
               "Each pupil's route and stop sit on their record, and transport bills with fees. Drivers see the list for their route.",
               ("photo", "classroom-zambia.jpg", "center 40%", [("transport_card", 0, 80)]))],
    ),
    "t-boarding": dict(
        name="Boarding schools", h="Run the hostel and the classroom on one record.",
        b="Houses, exeats, roll call and boarding fees sit on each boarder's record, next to their marks and reports.",
        hero=("boys-reading.jpg", "center 40%", "rollcall_card", "exeat_card"),
        depts=["boarding", "academics", "fees", "communication", "stock", "insights"],
        rows=[("Houses", "boarding", "Every boarder accounted for at lights out.",
               "Housemasters take roll call on a phone, house by house, with or without internet. Exeats and the sick bay show on the same list.",
               ("plate", [("rollcall_card", 160, 40)], "boarding")),
              ("Boarding fees", "fees", "Bill boarding and tuition on one account.",
               "Boarding, tuck and outings bill to the same family account, in US dollars and ZiG. Guardians pay by EcoCash or bank transfer.",
               ("photo", "boys-reading-2.jpg", "47% 42%", [("fee_card", 0, 80)]))],
    ),
    "t-government": dict(
        name="Government schools", h="Fees, levies and the figures your SDC asks for.",
        b="Bill tuition and levies in US dollars and ZiG, keep registers and term reports, and give your School Development Committee current figures.",
        hero=("rural-school.jpg", "center 35%", "levy_card", "head_card"),
        depts=["fees", "academics", "accounting", "communication", "stock", "insights"],
        rows=[("Fees and levies", "fees", "Bill tuition and levies the way your SDC sets them.",
               "Set tuition, levies and building funds by form, in US dollars and ZiG. Every payment gets a receipt and lands on the pupil's account.",
               ("plate", [("levy_card", 160, 40)], "fees")),
              ("SDC staff", "hr-payroll", "Pay the staff your SDC employs.",
               "The government pays its teachers. Campus runs payroll for the staff your SDC employs, and keeps a record for every member of staff.",
               ("photo", "teacher-class.jpg", "center 30%", [("payslip_card", 0, 60)]))],
    ),
    "t-private": dict(
        name="Private schools", h="A portal for every family, and figures for the board.",
        b="Admissions, fees, reports and a Parent portal for every family, with the figures your board asks for each term.",
        hero=("teens-courtyard.jpg", "center 40%", "application_card", "head_card"),
        depts=["admissions", "academics", "fees", "accounting", "hr-payroll", "insights"],
        rows=[("Admissions", "admissions", "Fill your places from one list.",
               "Enquiries, applications, entrance tests and offers in one list, with deposits linked to fees. You see how many places are left.",
               ("plate", [("intake_card", 160, 40)], "admissions")),
              ("Parent portal", "Parent", "Show parents the term as it happens.",
               "Attendance, marks, fees and reports reach each family's phone that week, with a line to the class teacher.",
               ("phone",))],
    ),
    "t-mission": dict(
        name="Mission schools", h="Day scholars and boarders on one record.",
        b="Run day and boarding pupils side by side on one record, with the reports the church that runs your school asks for.",
        hero=("mission-pupils.jpg", "center 35%", "register_card", "rollcall_card"),
        depts=["boarding", "academics", "fees", "accounting", "communication", "insights"],
        rows=[("Day and boarding", "t-mission", "Day scholars and boarders on one register.",
               "Mark day scholars and boarders on one class register. Boarders also appear on their house's roll call, and fees bill by the type of place.",
               ("plate", [("register_card", 160, 30)], "boarding")),
              ("Responsible authority", "insights", "Send the church the figures it asks for.",
               "Enrolment, results and finances for the responsible authority, from the records the school already keeps.",
               ("photo", "teacher-garden.jpg", "center 30%", [("results_card", 0, 80)]))],
    ),
}
TYPE_DEPTS_H = "What you run on Campus"

# Roles. slug, portal, hero, rows, depts
ROLE_PAGES = {
    "leadership": dict(
        name="School leadership", portal="Administration", h="See the whole school before the first lesson.",
        b="The Head's view shows attendance, fees, results and staffing from the record, for the Head, the deputies and the SDC or board.",
        hero=("teacher-garden.jpg", "center 30%", "head_card", "approvals_card"),
        rows=[("Attendance", "insights", "Know who is in school by 08:05.",
               "Registers come in from every classroom, online or not. You see attendance by form and the pupils who have missed the most.",
               ("plate", [("attendance_card", 150, 40)], None)),
              ("Approvals", "sent", "Approve payroll, leave and offers from your phone.",
               "Everything waiting for the Head sits in one list. Approve it and the bursary, the staffroom or the family hears straight away.",
               ("photo", "man-laptop.jpg", "center 30%", [("approvals_card", 0, 80)])),
              ("The board", "record", "Take current figures to every meeting.",
               "Fees collected, results and enrolment for the SDC or board, with every figure opening the records behind it.",
               ("plate", [("collected_card", 40, 40)], "insights"))],
        depts=["insights", "hr-payroll", "academics"],
    ),
    "bursary": dict(
        name="The bursary", portal="Administration", h="Fees, payroll and the books in one place.",
        b="Bill families, match payments, run payroll and keep the ledger, all from the same record the rest of the school uses.",
        hero=("office-desk.jpg", "center 30%", "payments_card", "payrun_card"),
        rows=[("Payments", "fees", "Match every payment to a pupil.",
               "EcoCash, bank and cash payments land on the pupil's account with a receipt number. Families see the same balance you do.",
               ("plate", [("payments_card", 150, 40)], None)),
              ("Payroll", "hr-payroll", "Run payroll from the staff record.",
               "PAYE, AIDS levy and NSSA come from each staff record. The Head approves the run and payslips go out on payday.",
               ("photo", "accounts-desk.jpg", "center 40%", [("payslip_card", 0, 60)])),
              ("Month-end", "accounting", "Close the month with the books up to date.",
               "Fees, payroll and purchases are already in the ledger. Send the journal to Sage Pastel or QuickBooks and you are done.",
               ("plate", [("journal_card", 40, 40)], "accounting"))],
        depts=["fees", "accounting", "hr-payroll"],
    ),
    "teachers": dict(
        name="Teachers", portal="Teacher", h="Registers, marks and reports in minutes.",
        b="Mark the register on a tablet, enter marks once and write reports from the same record, in class or in the staffroom.",
        hero=("teacher-tablet.jpg", "center 25%", "register_card", "marks_card"),
        rows=[("Registers", "academics", "Mark the register before the first lesson.",
               "Tap who is absent on a tablet or phone. It saves without internet and the office sees it by 08:05.",
               ("plate", [("register_card", 150, 30)], None)),
              ("Marks", "record", "Enter a mark once. It appears on the report.",
               "Marks feed term reports as you enter them. Averages and positions fill in, and parents see the mark that week.",
               ("photo", "teacher-class.jpg", "center 30%", [("marks_card", 0, 80)])),
              ("Parents", "communication", "Reply to parents without giving out your number.",
               "Parents message you in the Parent portal. You reply from the Teacher portal, and the conversation stays on the pupil's record.",
               ("plate", [("compose_card", 40, 50)], "academics"))],
        depts=["academics", "communication", "hr-payroll"],
    ),
    "boarding-staff": dict(
        name="Boarding staff", portal="Administration", h="Roll call, exeats and the sick bay, house by house.",
        b="Housemasters, matrons and duty teachers work from each boarder's record, on a phone, with or without internet.",
        hero=("girls-smiling.jpg", "center 35%", "rollcall_card", "sickbay_card"),
        rows=[("Roll call", "boarding", "Know who is in the house at lights out.",
               "Mark each boarder on a phone. Anyone not marked shows at the top, with where they were last seen.",
               ("plate", [("rollcall_card", 160, 40)], None)),
              ("Exeats", "sent", "Approve exeats and know who collected whom.",
               "Guardians request exeats in the Parent portal. You approve them, and the house list shows who is out and when they are due back.",
               ("photo", "boys-reading.jpg", "center 40%", [("exeat_card", 0, 80)])),
              ("Sick bay", "support", "Tell guardians and class teachers in one step.",
               "Log a sick bay visit and Campus tells the guardian and the class teacher. The visit stays on the boarder's record.",
               ("plate", [("sickbay_card", 40, 40)], "boarding"))],
        depts=["boarding", "communication", "academics"],
    ),
    "parents": dict(
        name="Parents and guardians", portal="Parent", h="Your child's week, on your phone.",
        b="Attendance, marks, fees and reports in the Parent portal, on any phone. Pay fees by EcoCash and message the class teacher.",
        hero=("father-son.jpg", "center 30%", "note_card", "fee_card"),
        rows=[("Marks and reports", "record", "See each mark the week it is recorded.",
               "Marks, attendance and term reports appear in the Parent portal as the school records them. Nobody waits for the end of term.",
               ("phone",)),
              ("Fees", "fees", "Pay fees and keep every receipt.",
               "See the balance and the due date on the first screen. Pay by EcoCash or bank transfer, and the receipt arrives in the portal.",
               ("plate", [("fee_card", 150, 40)], None)),
              ("Messages", "communication", "Message the class teacher directly.",
               "Write to the class teacher from the portal. The reply comes back to you, not to a group.",
               ("photo", "mother-phone.jpg", "65% center", [("note_card", 0, 90)]))],
        depts=["communication", "fees", "academics"],
    ),
    "pupils": dict(
        name="Pupils", portal="Student", h="Timetable, homework and marks on one sign-in.",
        b="Pupils see their timetable, homework and marks in the Student portal, on their own device or a school laptop.",
        hero=("kids-laptop.jpg", "center 40%", "student_card", "marks_card"),
        rows=[("Timetable", "calendar-t", "Know where the next lesson is.",
               "The day's lessons, rooms and teachers, updated when the timetable changes.",
               ("plate", [("student_card", 150, 40)], None)),
              ("Homework", "academics", "See homework and hand it in on time.",
               "Homework and due dates from every teacher in one list, with marks when they come back.",
               ("photo", "boys-laptop.jpg", "center", [("marks_card", 0, 80)])),
              ("Library", "ai", "Read the school's library and ask it questions.",
               "With Campus with LMS and e-library, pupils read the school's own library and ask it questions. Each use is logged, and the school can switch AI off.",
               ("plate", [("ai_card", 40, 40)], None))],
        depts=["academics", "communication", "boarding"],
    ),
}
ROLE_DEPTS_H = "The parts of Campus you use"

# ---- index pages ------------------------------------------------------------------------------------
SOLUTIONS = dict(eyebrow="Solutions", h="Software for every department in your school.",
                 b="Nine departments on one record. Each works in its own part of Campus and reads the same figures as the rest.")
WHO = dict(eyebrow="Who we serve · K-12", h="Made for K-12 schools, from ECD to Upper Sixth.",
           b="Day and boarding schools, government, private and mission, primary and secondary. The office, the staffroom and the hostel work from one record.",
           types_h="Types of school")

PLATFORM = dict(
    eyebrow="Platform", h="One record behind every department.",
    b="Campus is cloud-based school management software. Every department reads and writes one record, and the whole system works without internet.",
    portals_h="Four portals, one sign-in.",
    portals=[("Administration", "The office, the bursary and the Head.", "Fees, payroll, admissions and the Head's view."),
             ("Teacher", "The staffroom and the classroom.", "Registers, marks, reports and messages to parents."),
             ("Parent", "Guardians, on any phone.", "Attendance, marks, fees and the class teacher."),
             ("Student", "Pupils, on their own device or a school laptop.", "Timetable, homework, marks and the library.")],
    ai=("AI that assists", "AI that answers from your school's own material.",
        "In Campus with LMS and e-library, pupils and teachers ask questions of the school's lessons and library. Each use is logged, and the school can switch AI off."),
    more_h="More on the platform",
)

INTEG = dict(
    eyebrow="Integrations", h="Connect the software your bursar already uses.",
    b="Campus sends journals to Sage Pastel and QuickBooks, issues fiscal receipts through ZIMRA, and matches EcoCash and bank payments to each pupil. Add more from the Corelith Plugins and Integrations Hub.",
    market_eye="Plugins and integrations", market_h="Add the rest from the Corelith Plugins and Integrations Hub.",
    rows=[("Sage Pastel", "integrations", "Post the day's journal to Sage Pastel.",
           "Fees, payroll and purchases go to your Pastel ledger as one journal, mapped to your chart of accounts. Your accountant keeps working in Pastel.",
           "journal_card", "Sage Pastel"),
          ("QuickBooks", "integrations", "Keep QuickBooks in step with the bursary.",
           "Invoices, payments and journals reach QuickBooks without anyone retyping them. Each entry carries the receipt number from Campus.",
           "journal_card", "QuickBooks"),
          ("ZIMRA fiscalisation", "pricesheet", "Issue fiscal receipts through ZIMRA.",
           "Every receipt goes through ZIMRA's Fiscalisation Data Management System (FDMS), with the verification code and QR code printed on it.",
           "fiscal_card", None),
          ("Payments", "fees", "Match EcoCash and bank payments to each pupil.",
           "Payments arrive with a reference and land on the right account. The family gets a receipt and the bursar sees the balance change.",
           "payments_card", None)],
    faq=[("Do we have to change our accounting software?", "No. Campus sends journals to the Sage Pastel or QuickBooks you use now."),
         ("Who sets up the links?", "We do, during setup, with your bursar and your accountant."),
         ("How do we add an integration?", "From the Corelith Plugins and Integrations Hub, in the Administration portal. The Head or the bursar adds it, and we help with the setup."),
         ("Do the links cost extra?", "No. Pastel, QuickBooks and ZIMRA are part of Campus at US$1 per active pupil per month.")],
)

PRICE = dict(
    eyebrow="Pricing", h="US$1 per active pupil per month.",
    b="No licence fee and no charge per user. You pay for pupils on the roll in the months the school is open.",
    calc_h="Work out your school",
    calc_b="Enter the number of pupils on your roll. The figure is what you pay each month the school is open, and the first month is free.",
    incl_h="What is included",
    included=[("included", "Every department", "All nine, from admissions to the Head's view."),
              ("portals", "Four portals", "Administration, Teacher, Parent and Student."),
              ("integrations", "Pastel, QuickBooks and ZIMRA", "Journals and fiscal receipts."),
              ("nointernet", "Works without internet", "Every portal, on every device."),
              ("moving", "Setup and data capture", "We move your records, free."),
              ("training", "Training at your school", "Two weeks in the office and staffroom."),
              ("support", "Support from Harare", "Through the term and after."),
              ("security", "Daily backups", "And a full export whenever you want it.")],
    setup_h="Setup and training",
    setup_b="Two weeks to set up and move your records, two weeks of training at your school, then support for the rest of the term.",
    faq_h="Questions",
)

DEMO = dict(eyebrow="Book a demo", h="See Campus at your school.",
            b="We come to the school, set up a demo with your forms and fee structure, and walk the Head and the bursar through it in an afternoon.",
            next_h="What happens next",
            steps=[("1", "We call you", "We call the number you give us to agree a day for the visit."),
                   ("2", "We set up your school", "We load your forms and fee structure, so the demo shows your school."),
                   ("3", "We visit", "We walk the Head and the bursar through Campus at the school.")],
            agenda_h="An afternoon at your school, with your own records.",
            agenda=[("14:00", "The Head's office", "The Head's view, with your figures",
                     "Attendance, fees and results for your school, from the records you send us before the visit.", "head_card"),
                    ("14:40", "The bursary", "Bill a term and match a payment",
                     "Your fee structure is loaded. We match an EcoCash payment to a pupil while you watch.", "payments_card"),
                    ("15:20", "The staffroom", "Mark a register with the internet off",
                     "A teacher marks Form 3B on a tablet offline, turns the internet back on and watches it sync.", "register_card"),
                    ("16:00", "Back with the Head", "Your plan and your price",
                     "How we move your records, when we train your staff, and what Campus costs for your roll.", "plan_card")],
            who=("Who to invite", "portals", "Bring the people who will use it.",
                 "The Head, the bursar and a class teacher each see the part of Campus they will use. If you board, bring a housemaster too."),
            faq_h="Before the visit.",
            faq=[("What do we send before the visit?", "Your class lists and fee structure, in any form: an export, Excel sheets or photos of the registers. We load them so the demo shows your school."),
                 ("How long does it take?", "An afternoon. We fit it around your timetable."),
                 ("Do we need internet at the school?", "No. Part of the demo is Campus working with the internet off."),
                 ("Does the demo cost anything?", "No.")])
SENT = dict(h="Request sent.", b="We will call +263 77 000 0000 to arrange a visit to Mukuvisi High School.",
            next_h="While you wait")

SIGNIN = dict(h="Sign in to Campus", school="Mukuvisi High School",
              note="One sign-in for all four portals. Campus opens the portal for your role.",
              offline="Signed in on this device before? You can keep working without internet.")

CONTACT = dict(eyebrow="Contact", h="Talk to the Campus team.",
               b="We are in Harare. Book a demo, ask about pricing, or get help if your school already uses Campus.",
               routes=[("demo", "Book a demo", "See Campus at your school, with your own forms and fees.", "Book a demo"),
                       ("support", "Schools on Campus", "Message support from Help in any portal, or see the guides.", "Go to support"),
                       ("contact", "Anything else", "Partnerships, press and questions about Corelith.", "Write to us")],
               form_h="Write to us", form_hh="Write to the team in Harare.",
               form_b="Tell us what it is about. We read every message and reply by email.",
               topics=["Partnerships", "Press", "Pricing", "Something else"])

SUPPORT = dict(eyebrow="Support", h="Help for schools on Campus.",
               b="Find a guide, or message support from Help in any portal.",
               topics=[("included", "Getting started", ["Sign in for the first time", "Add a member of staff", "Set up a new term"]),
                       ("academics", "Registers and marks", ["Mark a register offline", "Enter marks for a test", "Publish term reports"]),
                       ("fees", "Fees and receipts", ["Bill a new term", "Match an EcoCash payment", "Reprint a receipt"]),
                       ("hr-payroll", "Payroll", ["Run the monthly payroll", "Change a staff member's bank details", "Send payslips"]),
                       ("Parent", "Parent portal", ["Send a guardian their sign-in", "Reset a guardian's password", "Link siblings"]),
                       ("nointernet", "Working without internet", ["How sync works", "See changes waiting to sync", "Sync now"])],
               reach_h="Talk to us",
               reach=[("support", "Message support", "Open Help in any portal and write to us. Your message reaches the team in Harare.", "Open Help"),
                      ("training", "Book a training visit", "New staff, or a new term? We come back to the school and train them.", "Book a visit")])

LEGAL_UPDATED = "Last updated 1 October 2026"
LEGAL = {
    "privacy": dict(title="Privacy", h="How we handle personal data.", sections=[
        ("Who we are", "Corelith Labs runs Corelith Campus from Harare. When a school uses Campus, the school decides what data goes in and why. We process it for the school and follow its instructions."),
        ("What we hold", "The records the school keeps: pupils, guardians, staff, marks, attendance, fees and payroll. For people who use this website or book a demo, we hold the name, role, school, phone number and email address they give us."),
        ("How we use it", "We use school records to run Campus for the school, to support and train its staff, and to keep the service secure. We use demo requests only to arrange the demo."),
        ("What we never do", "We do not sell personal data or use it for advertising. AI features read only the school's own material, each use is logged, and the school can switch AI off."),
        ("Who can see it", "Each person sees what their role needs. A guardian sees only their own children. Every change records who made it and when."),
        ("Where it is kept", "Campus runs in the cloud and is backed up every day. Data saved on a device while it is offline syncs to the cloud when the connection returns."),
        ("How long we keep it", "We keep a school's data while it uses Campus. When a school leaves, it takes its export, and we then delete its data."),
        ("Your rights", "Pupils, guardians and staff can ask their school to see, correct or delete their data. The school handles the request, and we help it."),
        ("Questions", "Write to us through the contact page and we will reply.")]),
    "data": dict(title="Data ownership", h="Your school's data stays yours.", sections=[
        ("The data belongs to the school", "Everything the school puts into Campus belongs to the school. We hold it only to run the service."),
        ("Export everything, at any time", "The Head or the bursar can export the whole record: pupils, guardians, staff, marks, fees and payroll, in files Excel and other systems open."),
        ("If you leave", "Your export stays available until you confirm you have it. We then delete the school's data from Campus."),
        ("Who sees what", "Each person sees what their role needs, and every change records who made it and when."),
        ("Backups", "Campus is backed up every day, so a mistake or a lost device does not lose the school's records."),
        ("Offline copies", "A device keeps what its user needs to work without internet. It syncs when the connection returns."),
        ("AI", "AI features read only the school's own material. Each use is logged, and the school can switch AI off.")]),
    "terms": dict(title="Terms", h="The terms, in plain words.", sections=[
        ("The service", "Corelith Labs provides Corelith Campus, cloud-based school management software, to the school named in its order."),
        ("Price", "Campus is US$1 per active pupil per month. Campus with LMS and e-library is US$8.99 per active pupil per month and replaces the US$1 rate."),
        ("Billing", "An active pupil is a learner on the roll in the month we bill. We do not bill in the school holidays. The first month is free."),
        ("Setup and training", "Setup, data capture and training are free."),
        ("Your data", "The school owns its data and can export it at any time. Our data ownership page sets out how."),
        ("Working without internet", "Campus works without internet. Work saved on a device syncs when the connection returns."),
        ("Ending the agreement", "Either side can end the agreement as the school's order sets out. The school keeps its export."),
        ("Changes to these terms", "We tell schools before these terms change."),
        ("Law", "These terms are governed by the laws of Zimbabwe.")]),
}
